<?php

namespace Administration\PharmacieBundle\Repository;

/**
 * PharmacieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PharmacieRepository extends \Doctrine\ORM\EntityRepository
{
}
