<?php

namespace Pharmacie\StockBundle\Repository;

/**
 * CategorieRepositor
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{

}
