<?php

namespace Pharmacie\StockBundle\Repository;

/**
 * ChampProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
