<?php

namespace Pharmacie\StockBundle\Repository;

/**
 * ChampDynamiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampDynamiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
