<?php

namespace Pharmacie\InventaireBundle\Repository;

/**
 * ModeleInventaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleInventaireRepository extends \Doctrine\ORM\EntityRepository
{
}
