<?php

namespace Gestion\InventaireBundle\Repository;

/**
 * TypeInventaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeInventaireRepository extends \Doctrine\ORM\EntityRepository
{
}
