Gestion\StockBundle\Entity\Client:
    type: entity
    table: client
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        cin:
            type: string
            nullable: false
            length: 90
            options:
                fixed: false
        tel:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
        mail:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
    lifecycleCallbacks: {  }
