Gestion\StockBundle\Entity\Pharmacien:
    type: entity
    table: pharmacien
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        statut:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
        tel:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
        mail:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
    lifecycleCallbacks: {  }
