Gestion\StockBundle\Entity\Produitvendu:
    type: entity
    table: produitvendu
    uniqueConstraints:
        UNIQ_6A830A89C29D63C1:
            columns:
                - idproduit_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        quantite:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
    manyToOne:
        idproduit:
            targetEntity: Produit
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idproduit_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
