Gestion\StockBundle\Entity\Typevente:
    type: entity
    table: typevente
    uniqueConstraints:
        UNIQ_2A09F5FF4A44E93:
            columns:
                - idachete_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        typevente:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        pourcentage:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
    manyToOne:
        idachete:
            targetEntity: Achete
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idachete_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
