<?php

namespace Pharmacie\VenteBundle\Repository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
	 public function findArray($array){
        $bg=$this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.id IN (:array)')
            ->setParameter('array',$array);
        return $bg->getQuery()->getResult();


    }
}
