gestion_inventaire_homepage:
    path:     /inventaire
    defaults: { _controller: GestionInventaireBundle:Inventaire:index }


generer_pdf_inventaire:
    path:     /inventaire/pdf
    defaults: { _controller: GestionInventaireBundle:Inventaire:pdf }