<?php

namespace Proxies\__CG__\Administration\PharmacieBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pharmacie extends \Administration\PharmacieBundle\Entity\Pharmacie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'id', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'code', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'nom', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'adresse', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'arrondissement', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'ville', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'departement', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'region', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'latitude', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'longitude', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'dateCreation', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'telephone', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'email', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'siteWeb'];
        }

        return ['__isInitialized__', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'id', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'code', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'nom', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'adresse', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'arrondissement', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'ville', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'departement', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'region', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'latitude', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'longitude', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'dateCreation', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'telephone', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'email', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacie' . "\0" . 'siteWeb'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pharmacie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setArrondissement($arrondissement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArrondissement', [$arrondissement]);

        return parent::setArrondissement($arrondissement);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrondissement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrondissement', []);

        return parent::getArrondissement();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartement($departement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartement', [$departement]);

        return parent::setDepartement($departement);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartement', []);

        return parent::getDepartement();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegion($region)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegion', [$region]);

        return parent::setRegion($region);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegion', []);

        return parent::getRegion();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', [$latitude]);

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', []);

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', [$longitude]);

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', []);

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiteWeb($siteWeb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiteWeb', [$siteWeb]);

        return parent::setSiteWeb($siteWeb);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiteWeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiteWeb', []);

        return parent::getSiteWeb();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
