gestion_vente_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PharmacieVenteBundle:Default:index }

gestionstock_ajouter_client:
    path:     /client/ajouter
    defaults: { _controller:  PharmacieVenteBundle:client:ajouter }


gestionstock_client_achete:
    path:     /achat/client
    defaults: { _controller: PharmacieVenteBundle:Achete:client }

gestionstock_clientajouter_achete:
    path:     /achat/clientajouter
    defaults: { _controller: PharmacieVenteBundle:Achete:clientajouter }


# gestionstock_ajouter_achete:
#     path:     /achat/ajouter
#     defaults: { _controller: PharmacieVenteBundle:Achete:ajouter }
gestionstock_ajouter_achete:
    path:     /achat/ajouter
    defaults: { _controller: PharmacieVenteBundle:Achete:panier }



# gestionstock_modifier_achete:
#     path:     /achat/modier/{id}
#     defaults: { _controller:  PharmacieVenteBundle:Achete:modifier }

gestionstock_modifier_achete:
    path:     /achat/modifier/
    defaults: { _controller:  PharmacieVenteBundle:Achete:modifier }

gestionstock_panier_achete:
    path:     /achat/panier
    defaults: { _controller:  PharmacieVenteBundle:Achete:panier }


gestionstock_panier_achete_client:
    path:     /achat/panier/client
    defaults: { _controller:  PharmacieVenteBundle:Achete:infoClient }



gestionstock_validerpanier_achete:
    path:     /valider/panier
    defaults: { _controller:  PharmacieVenteBundle:Achete:validerpanier }
gestionstock_valider_achete:
    path:     /valider1/panier
    defaults: { _controller:  PharmacieVenteBundle:Achete:valider }

gestionstock_panierajouter_achete:
    path:     /achat/panierajouter/{id}
    defaults: { _controller: PharmacieVenteBundle:Achete:panierajouter }



gestionstock_paier_supprimer:
    path:     /achat/supprimer/{id}
    defaults: { _controller:  PharmacieVenteBundle:Achete:supprimer }

gestionstock_lister_achete:
    path:     /achat/lister
    defaults: { _controller: PharmacieVenteBundle:Achete:lister }
gestionstock_recherche_achete:
    path:     /achat/recherche
    defaults: { _controller:  PharmacieVenteBundle:Achete:recherche }
gestionstock_affiche_achete:
    path:     /achat/affiche/{id}
    defaults: { _controller:  PharmacieVenteBundle:Achete:affiche }
gestionstock_lister_achete_produitVendu:
    path:     /achat/listervente
    defaults: { _controller: PharmacieVenteBundle:Achete:listervente }
gestionstock_lister_achete_vente:
    path:     /achat/vente/{id}
    defaults: { _controller: PharmacieVenteBundle:Achete:vente }