<?php

namespace Gestion\VenteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Select;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
    public function findArray($array){
        $bg=$this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.id IN (:array)')
            ->setParameter('array',$array);
        return $bg->getQuery()->getResult();


    }

    public function findArray1($array){
        $bg=$this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.id IN (:array)')
            ->setParameter('array',$array);
        return $bg->getQuery()->getResult();


    }
}

