gestion_stock_homepage:
    path:     /produit
    defaults: { _controller: PharmacieStockBundle:Produit:index }

#  produit
gestion_stock_ajouter_produit:
    path:     /produit/ajouter
    defaults: { _controller: PharmacieStockBundle:Produit:ajouter }

gestion_stock_afficher_produit:
    path:     /produit/afficher/{code}
    defaults: { _controller: PharmacieStockBundle:Produit:afficher }

gestion_stock_lister_produit:
    path:     /produit/lister
    defaults: { _controller: PharmacieStockBundle:Produit:lister }

gestion_stock_modifier_produit:
    path:     /produit/modifier/{codebarre}
    defaults: { _controller: PharmacieStockBundle:Produit:modifier }

gestion_stock_supprimer_produit:
    path:     /produit/supprimer/{codebarre}
    defaults: { _controller: PharmacieStockBundle:Produit:supprimer }

gestion_stock_produit_statistiques:
    path:       /produit/statistiques
    defaults:   { _controller: PharmacieStockBundle:Produit:VoirStats1 }





# stock    
gestion_stockage_lister_stock:
    path:     /stock/lister
    defaults: { _controller: PharmacieStockBundle:Stock:lister }

gestion_stockage_afficher_stock:
    path:     /stock/afficher/{id}
    defaults: { _controller: PharmacieStockBundle:Stock:afficher }

gestion_stockage_ajouter_stock:
    path:     /stock/ajouter
    defaults: { _controller: PharmacieStockBundle:Stock:ajouter }

gestion_stockage_modifier_stock:
    path:     /stock/modifier/{id}
    defaults: { _controller: PharmacieStockBundle:Stock:modifier }

gestion_stockage_supprimer_stock:
    path:     /stock/supprimer/{id}
    defaults: { _controller: PharmacieStockBundle:Stock:supprimer }

gestion_stock_stock_statistiques:
    path:       /stock/statistiques
    defaults:   { _controller: PharmacieStockBundle:Stock:statistiques }


# categorie
gestion_stock_categorie:
    path:       /categorie
    defaults:   {_controller: PharmacieStockBundle:Categorie:index}

gestion_stock_categorie_ajouter:
    path:       /categorie/ajouter
    defaults:   {_controller: PharmacieStockBundle:Categorie:ajouter}

gestion_stock_categorie_lister:
    path:       /categorie/lister
    defaults:   {_controller: PharmacieStockBundle:Categorie:lister}

gestion_stock_categorie_modifier:
    path:       /categorie/modifer/{id}
    defaults:   {_controller: PharmacieStockBundle:Categorie:modifier}

gestion_stock_categorie_supprimer:
    path:       /categorie/supprimer/{id}
    defaults:   {_controller: PharmacieStockBundle:Categorie:supprimer}

gestion_stock_categorie_afficher:
    path:     /categorie/afficher/{id}
    defaults: { _controller: PharmacieStockBundle:Categorie:afficher }

gestion_stock_categorie_produit:
    path:       /categorie/produit/{id}
    defaults:   {_controller: PharmacieStockBundle:Categorie:produitCategorie}


gestion_stock_categorie_statistiques:
    path:       /categorie/statistiques
    defaults:   { _controller: PharmacieStockBundle:Categorie:statistiques }


gestion_stock_dynamique_produit_ajouter:
    path:       /dynamique/produit/ajouter
    defaults:   { _controller: PharmacieStockBundle:Dynamique:produitAjouter }



# gestion sous-categorie
gestion_stock_souscategorie:
    path:       /souscategorie
    defaults:   {_controller: PharmacieStockBundle:SousCategorie:index}

gestion_stock_souscategorie_ajouter:
    path:       /souscategorie/ajouter
    defaults:   {_controller: PharmacieStockBundle:SousCategorie:ajouter}

gestion_stock_souscategorie_lister:
    path:       /souscategorie/lister
    defaults:   {_controller: PharmacieStockBundle:SousCategorie:lister}

gestion_stock_souscategorie_modifier:
    path:       /souscategorie/modifer/{id}
    defaults:   {_controller: PharmacieStockBundle:SousCategorie:modifier}

gestion_stock_souscategorie_supprimer:
    path:       /souscategorie/supprimer/{id}
    defaults:   {_controller: PharmacieStockBundle:SousCategorie:supprimer}

gestion_stock_souscategorie_afficher:
    path:       /souscategorieafficher/{id}
    defaults:   {_controller: PharmacieStockBundle:SousCategorie:afficher}



# requetes dynamiques avec ajax
gestion_stock_ajax_produit:
    path:   /ajax/produit
    defaults: {_controller: PharmacieStockBundle:Produit:whenCategorieChange}
    requirements:
        _method: GET
