gestion_stock_homepage:
    path:     /produit
    defaults: { _controller: PharmacieStockBundle:Produit:index }

gestion_stock_ajouter_produit:
    path:     /produit/ajouter
    defaults: { _controller: PharmacieStockBundle:Produit:ajouter }

gestion_stock_afficher_produit:
    path:     /produit/afficher/{code}
    defaults: { _controller: PharmacieStockBundle:Produit:afficher }

gestion_stock_lister_produit:
    path:     /produit/lister
    defaults: { _controller: PharmacieStockBundle:Produit:lister }

gestion_stock_modifier_produit:
    path:     /produit/modifier/{codebarre}
    defaults: { _controller: PharmacieStockBundle:Produit:modifier }

gestion_stock_supprimer_produit:
    path:     /produit/supprimer/{codebarre}
    defaults: { _controller: PharmacieStockBundle:Produit:supprimer }

gestion_stock_produit_statistiques:
    path:       /produit/statistiques
    defaults:   { _controller: PharmacieStockBundle:Produit:statistiques }


    
gestion_stockage_lister_stock:
    path:     /stock/lister
    defaults: { _controller: PharmacieStockBundle:Stock:lister }

gestion_stockage_afficher_stock:
    path:     /stock/afficher/{id}
    defaults: { _controller: PharmacieStockBundle:Stock:afficher }

gestion_stockage_ajouter_stock:
    path:     /stock/ajouter
    defaults: { _controller: PharmacieStockBundle:Stock:ajouter }

gestion_stockage_modifier_stock:
    path:     /stock/modifier/{id}
    defaults: { _controller: PharmacieStockBundle:Stock:modifier }

gestion_stockage_supprimer_stock:
    path:     /stock/supprimer/{id}
    defaults: { _controller: PharmacieStockBundle:Stock:supprimer }


gestion_stock_categorie:
    path:       /categorie
    defaults:   {_controller: PharmacieStockBundle:Categorie:index}

gestion_stock_categorie_ajouter:
    path:       /categorie/ajouter
    defaults:   {_controller: PharmacieStockBundle:Categorie:ajouter}

gestion_stock_categorie_lister:
    path:       /categorie/lister
    defaults:   {_controller: PharmacieStockBundle:Categorie:lister}

gestion_stock_categorie_modifier:
    path:       /categorie/modifer/{id}
    defaults:   {_controller: PharmacieStockBundle:Categorie:modifier}

gestion_stock_categorie_supprimer:
    path:       /categorie/supprimer/{id}
    defaults:   {_controller: PharmacieStockBundle:Categorie:supprimer}

gestion_stock_categorie_produit:
    path:       /categorie/produit/{id}
    defaults:   {_controller: PharmacieStockBundle:Categorie:produitCategorie}


gestion_stock_categorie_statistiques:
    path:       /categorie/statistiques
    defaults:   { _controller: PharmacieStockBundle:Categorie:statistiques }


gestion_stock_dynamique_produit_ajouter:
    path:       /dynamique/produit/ajouter
    defaults:   { _controller: PharmacieStockBundle:Dynamique:produitAjouter }
