services:
#    gestion_stock.example:
#        class: Gestion\StockBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    Gestion.StockBundle.basedd:
        class: Gestion\StockBundle\Service\BaseDD
        arguments: ['@doctrine.orm.entity_manager']

